name: module3_task0
on:
  schedule:
    - cron: "0 0 * * *"
  push:
jobs:
  deploy:
    runs-on: ubuntu-lastest
    steps:
      - name: Clone the current repository
        uses: actions/checkout@v3
      - name: Changue the current directory
        run: cd module3_task0
      - name: Run the command make help
        run: make help
