name: module3_task1
on:
  schedule:
    - cron: "0 0 * * *"
  push:
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone the current repository
        uses: actions/checkout@v3
      - name: Changue the current directory
        run: cd module3_task1 && source setup.sh
      - name: try a make clean
        run: cd module3_task1 && make clean
      - name: try a make post
        run: cd make POST_TITLE="my new post" POST_NAME="file" post
      - name: try a make build
        run: cd module3_task1 && make build
      - name: try make help
        run: cd module3_task1 && make help
