name: module3_task0
on:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    working-directory: module3_task1
    steps:
      - name: Clone the current repository
        uses: actions/checkout@v3
      - name: Changue the current directory
        run: source setup.sh
      - name: try a make clean
        run: make clean
      - name: try a make post
        run: make post
        env: POST_TITLE=file POST_NAME="Trying a new Post"
      - name: try a make build
        run: make build
      - name: try make help
        run: make help
